name: smart_agri
description: "Smart Agriculture IoT Management App"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_crashlytics: ^4.3.9
  firebase_analytics: ^11.5.2
  firebase_storage: ^12.4.9
  
  # Network & Communication
  http: ^1.4.0
  dio: ^5.8.0+1
  coap: ^9.1.2
  network_info_plus: ^6.1.4
  connectivity_plus: ^6.1.4
  
  # UI & Navigation
  material_symbols_icons: ^4.2815.1
  go_router: ^14.8.1
  flutter_riverpod: ^2.6.1
  
  # Charts & Data Visualization
  fl_chart: ^0.70.2
  
  # Data & Storage
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  path: ^1.9.0
  json_annotation: ^4.9.0
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  permission_handler: ^11.4.0
  device_info_plus: ^10.1.2
  package_info_plus: ^8.3.0
  
  # State Management & Architecture
  equatable: ^2.0.7
  
  # Loading & Progress
  loading_animation_widget: ^1.3.0
  flutter_spinkit: ^5.2.1
  
  # File handling
  file_picker: ^10.2.0
  csv: ^6.0.0
  
  # Fonts
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
